---

language: python

sudo: required

env:
  - distribution: centos
    version:      7
  - distribution: debian
    version:      stretch
  - distribution: debian
    version:      jessie
  - distribution: debian
    version:      buster
  - distribution: debian
    version:      sid
# - distribution: fedora
#   version:      rawhide
  - distribution: fedora
    version:      26
  - distribution: fedora
    version:      25
  - distribution: fedora
    version:      24
  - distribution: opensuse
    version:      tumbleweed
  - distribution: opensuse
    version:      42.3
  - distribution: opensuse
    version:      42.2
  - distribution: richxsl/rhel7
    version:      latest
  - distribution: ubuntu
    version:      xenial
  - distribution: ubuntu
    version:      trusty
  - distribution: ubuntu
    version:      bionic
  - distribution: ubuntu
    version:      rolling

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'

script:
  - container_id=$(mktemp -t XXXXXXXXXXXX)
  - container_id=$( basename $container_id )
  - 'docker run --detach --volume="$PWD":"$PWD":ro -w "$PWD" --name $container_id $distribution:$version sleep 2d'
  - 'docker exec -it $container_id sh -c "cd tests && pwd && ls -ld ./* ../* ../../* ../../../*"'
  - 'docker exec -it $container_id ./tests/env-prep.sh'
  - 'docker exec -it $container_id sh -c "cd tests && ./test.yml -l localhost -vv"'

