---

language: python

sudo: required

env:
  - distribution: centos
    version:      7
  - distribution: fedora
    version:      26
  - distribution: fedora
    version:      25
  - distribution: fedora
    version:      24
  - distribution: ubuntu
    version:      xenial
  - distribution: ubuntu
    version:      trusty
  - distribution: debian
    version:      stretch
  - distribution: debian
    version:      jessie

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - env | sort

script:
  - container_id=$(mktemp -t XXXXXXXXXXXX)
  - container_id=$( basename $container_id )
  - env | sort
  - 'docker run --detach --volume="$PWD":"$PWD":ro -w "$PWD" --name $container_id $distribution:$version pwd'
  - 'docker run --detach --volume="$PWD":"$PWD":ro -w "$PWD" --name $container_id $distribution:$version type curl'
