---

language: python

sudo: required

services:
  - docker

env:
  - distribution: registry.access.redhat.com/ubi8/ubi
    version:      latest

  - distribution: centos
    version:      latest
  - distribution: centos
    version:      8
  - distribution: centos
    version:      7

  - distribution: debian
    version:      sid-slim
  - distribution: debian
    version:      buster-slim

  - distribution: fedora
    version:      rawhide
  - distribution: fedora
    version:      33

  - distribution: ubuntu
    version:      rolling
  - distribution: ubuntu
    version:      focal

before_install:
  - 'sudo docker pull ${distribution}:${version}'

script:
  - container_id=$(mktemp -t XXXXXXXXXXXX)
  - container_id=$( basename $container_id )
  - 'docker run --detach --volume="$PWD":"$PWD":ro -w "$PWD" --name $container_id $distribution:$version sleep 2d'
  - 'docker exec -it $container_id sh -c "cd tests && pwd && ls -ld ./* ../* ../../* ../../../*" || true'
  - 'docker exec -it $container_id ./tests/env-prep.sh'
  - 'docker exec -it $container_id sh -c "cd tests && ./test.yml -l localhost -vv"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
