---

# tasks file for ansible-bootstrap-http-proxy

- name: Normalize proxy environment variables
  set_fact:
    "fact_{{ item.key }}={{ item.value }}"
  with_items:

    - key:   http_proxy
      value: '{{ http_proxy |
                 default(HTTP_PROXY, true) |
                 default("", true)
               }}'
    - key:   HTTP_PROXY
      value: '{{
          ( http_proxy is defined and http_proxy != "" ) |
            ternary(
              http_proxy,
              ( HTTP_PROXY | default("", true) )
            )
        }}'

    - key:   no_proxy
      value: '{{
                ( http_proxy is defined and http_proxy != "" ) |
                ternary (
                   no_proxy |
                   default(NO_PROXY, true) |
                   default(no_proxy_list | join(","), true),
                   ""
                )
              }}'
    - key:   NO_PROXY
      value: '{{
                ( http_proxy is defined and http_proxy != "" ) |
                ternary (
                   NO_PROXY |
                   default(no_proxy, true) |
                   default(no_proxy_list | join(","), true),
                   ""
                )
              }}'

    - key:   https_proxy
      value: '{{ https_proxy |
                 default(HTTPS_PROXY, true) |
                 default(http_proxy, true) |
                 default("", true)
              }}'
    - key:   HTTPS_PROXY
      value: '{{ HTTPS_PROXY |
                 default(https_proxy, true) |
                 default(http_proxy, true) |
                 default("", true)
              }}'

    - key:   ftp_proxy
      value: '{{ ftp_proxy |
                 default(FTP_PROXY, true) |
                 default(http_proxy, true) |
                 default("", true)
              }}'
    - key:   FTP_PROXY
      value: '{{ FTP_PROXY |
                 default(ftp_proxy, true) |
                 default(http_proxy, true) |
                 default("", true)
              }}'

  tags:
    - ftp_proxy
    - ftp-proxy
    - http_proxy
    - http-proxy
    - https_proxy
    - https-proxy
    - no_proxy
    - no-proxy

- name: Set proxy environment variables in /etc/environment
  raw:
    grep   '^{{ item.key }}' /etc/environment &&
      sed -i '/^{{ item.key }}=".*"$/d' /etc/environment;
    if [ '{{ item.value }}' != '' ]; then
      echo '{{ item.key }}="{{ item.value }}"' | tee -a /etc/environment;
    fi
  when:
    - item.value is defined
  with_items:

    - key:   ftp_proxy
      value: '{{ fact_ftp_proxy   | default("", true) }}'
    - key:   FTP_PROXY
      value: '{{ fact_FTP_PROXY   | default("", true) }}'

    - key:   http_proxy
      value: '{{ fact_http_proxy  | default("", true) }}'
    - key:   HTTP_PROXY
      value: '{{ fact_HTTP_PROXY  | default("", true) }}'

    - key:   https_proxy
      value: '{{ fact_https_proxy | default("", true) }}'
    - key:   HTTPS_PROXY
      value: '{{ fact_HTTPS_PROXY | default("", true) }}'

    - key:   no_proxy
      value: '{{ fact_no_proxy    | default("", true) }}'
    - key:   NO_PROXY
      value: '{{ fact_NO_PROXY    | default("", true) }}'

  register:
    tee_value
  changed_when:
    tee_value.stdout != ""
  tags:
    - ftp_proxy
    - ftp-proxy
    - http_proxy
    - http-proxy
    - https_proxy
    - https-proxy
    - no_proxy
    - no-proxy

