---

# tasks file for ansible-bootstrap-http-proxy

- name: Validate config
  set_fact:
    "{{ item.key }}={{ item.value }}"
  when:
    - |
      ( one_proxy is defined and one_proxy == True ) and
      ( ( http_proxy is defined or HTTP_PROXY is defined ) or
        ( no_proxy is defined or NO_PROXY is defined )
      )
  with_items:

    - key:   ftp_proxy
      value: '{{ ftp_proxy | default(FTP_PROXY, true) |
                 default( (one_proxy == True) | ternary(http_proxy, "") )
              }}'
    - key:   FTP_PROXY
      value: '{{ FTP_PROXY | default(ftp_proxy, true) |
                 default( (one_proxy == True) | ternary(http_proxy, "") )
              }}'

    - key:   http_proxy
      value: '{{ http_proxy | default(HTTP_PROXY, true) |
                 default( (one_proxy == True) | ternary(http_proxy, "") )
              }}'
    - key:   HTTP_PROXY
      value: '{{ HTTP_PROXY | default(http_proxy, true) |
                 default( (one_proxy == True) | ternary(http_proxy, "") )
              }}'

    - key:   https_proxy
      value: '{{ https_proxy | default(HTTPS_PROXY, true) |
                 default( (one_proxy == True) | ternary(http_proxy, "") )
              }}'
    - key:   HTTPS_PROXY
      value: '{{ HTTPS_PROXY | default(https_proxy, true) |
                 default( (one_proxy == True) | ternary(http_proxy, "") )
              }}'

    - key:   no_proxy
      value: '{{ no_proxy | default(NO_PROXY, true) |
                 default( no_proxy_list | join(","), true )
              }}'
    - key:   NO_PROXY
      value: '{{ NO_PROXY | default(no_proxy, true) |
                 default( no_proxy_list | join(","), true )
              }}'

  tags:
    - ftp_proxy
    - ftp-proxy
    - http_proxy
    - http-proxy
    - https_proxy
    - https-proxy
    - no_proxy
    - no-proxy

- name: Set proxy environment variables in /etc/environment
  raw:
    grep -qF '{{ item.key }}="{{ item.value }}"' /etc/environment ||
      ( sed -i '/^{{ item.key }}=".*"$/d' /etc/environment;
        echo '{{ item.key }}="{{ item.value }}"' |
        tee -a /etc/environment
      )
  with_items:

    - key:   ftp_proxy
      value: '{{ ftp_proxy   | default("", true) }}'
    - key:   FTP_PROXY
      value: '{{ FTP_PROXY   | default("", true) }}'

    - key:   http_proxy
      value: '{{ http_proxy  | default("", true) }}'
    - key:   HTTP_PROXY
      value: '{{ HTTP_PROXY  | default("", true) }}'

    - key:   https_proxy
      value: '{{ https_proxy | default("", true) }}'
    - key:   HTTPS_PROXY
      value: '{{ HTTPS_PROXY | default("", true) }}'

    - key:   no_proxy
      value: '{{ no_proxy    | default("", true) }}'
    - key:   NO_PROXY
      value: '{{ NO_PROXY    | default("", true) }}'

  when:
    - item.value is defined
    - item.value != ""
  register:
    tee_value
  changed_when:
    tee_value.stdout != ""
  tags:
    - ftp_proxy
    - ftp-proxy
    - http_proxy
    - http-proxy
    - https_proxy
    - https-proxy
    - no_proxy
    - no-proxy

